### ISSUE TITLE
 json.jsf marks valid number parts as error. 

### ISSUE THREAD

**Issue by oberdiek** [cmur2/joe-syntax#30]
The syntax highlighting of the JSON document

```
[1.23, 1.2e3]
```
marks `3` and `e3 ` with error coloring (white on red), but both numbers are valid JSON.
The error is in the following rule:

```
:integer Number
        *                       end             noeat
        "0-9"                   integer
        "."                     decimalpoint
        "eE"                    exponentpart
```
The target `decimalpoint` should be replaced by `decimalpart`:

```
:integer Number
        *                       end             noeat
        "0-9"                   integer
        "."                     decimalpart
        "eE"                    exponentpart
```

I have this also reported upstream, see [ticket #376](https://sourceforge.net/p/joe-editor/bugs/376/).

**Comment by cmur2** [comment]
Maybe @iarna has a clue what is wrong here? I tried it myself and can confirm this odd behavior.

**Comment by oberdiek** [comment]
I got a reply from the upstream bug report about the same issue:

> This was already fixed in Mercurial [[097380]](https://sourceforge.net/p/joe-editor/mercurial/ci/0973806c2a488db88575f7b945bd341ba12dd28c/) and will be included in the next version.

It is the same fix as provided in the bug report here.

**Comment by cmur2** [comment]
Thank for actively pursuing this bug here and upstream. I backported the upstream fix into https://github.com/cmur2/joe-syntax/commit/486ac0ec28e8bffc0faf502bbec306265f51eebb.
