### ISSUE TITLE
Markdown highlight with `[`

### ISSUE THREAD

**Issue by egmontkob** [cmur2/joe-syntax#36]
Hi,

( Forwarding from https://sourceforge.net/p/joe-editor/bugs/396/ )

Please see the attached test file.

Inside backticks everything is displayed literally in Markdown. Still, an opening bracket present there screws up the rest of the highlighting, in particular, the subsequent list items are not colored in blue in the test file.

Backslash-escaping the bracket fixes joe's highlighting, but breaks the file since it'll show up as a backspace in the rendered version.

[joemarkdown.md.txt](https://github.com/cmur2/joe-syntax/files/2667905/joemarkdown.md.txt)

**Comment by cmur2** [comment]
Thanks for the report, this can and should be fixed.

**Comment by cmur2** [comment]
This was fixed by @utoddl for the `master`/`joe-3.7` branch and thus should work directly if you use them. I will port this to the `joe-4.4` branch as well.
